### ISSUE TITLE
`--remove` kills indices that are still referenced by an alias

### ISSUE THREAD

**Issue by ldegen** [lxfrdl/esmeralda#2]
It seems Esmeralda is overly eager at dropping unused indices:

```sh
esmeralda --create foo   
```
Looking at http://localhost:9200/_cat/indices, I can see that an index `foo-#####` was created. There is also an aleas `foo-write` pointing to that index. No read alias is created at this point, which I think is correct.

Next, I do
```sh
esmeralda --swap foo
```
Now the alias `foo-write` is removed, and a new alias `foo` is created. Also correct.

But when I do
```sh
esmeralda --yes --older none --remove 'foo*'
```
esmeralda seems to remove both the index *and* the read alias. This is wrong, right? Or am I using it wrong?

**Comment by lxfrdl** [comment]
In the current state `--none` only expects numbers and handles them as days. I will publish a new version and amend an the ability, that you can pass **none** to `--older`. This will remove all matching and unreferenced indices.

**Comment by ldegen** [comment]
In addition, please make sure that esmeralda *never* *ever* drops an index that is still in use, i.e. has an alias pointing to it. :-)

**Comment by lxfrdl** [comment]
After discussing the problem again I see the current behaviour is not what we want.

If the are aliases pointing to an index we never want to delete it, cause this means it is still in use.
Otherwise we check if  `--older` is none, then we want to keep no indices.
Otherwise we check expect `--older` to be a number and check if the (index timestamp diff to now in days) is lower or equals the threshold. That means the index is valid, otherwise it is invalid and will be deleted.
